### PR TITLE
Upgrade to cdk v2

### PR DESCRIPTION
**Pull request by titanjer**
I used the following steps to do this job.

1. run `yarn install`
1. modify `requeire('awscdk');` in `.projenrc.js`
1. run `npx projen upgrade-projen`
1. modify `cdkVersion to v2` in `.projenrc.js` and run `npx projen`
1. run `npx -p aws-cdk-migration rewrite-imports-v2 ./**/*.ts`
1. fix test
1. remove unsupported feature flag for cdk v2
1. run `npm run test` and `npx cdk diff --app="npx ts-node src/integ.default.ts"` to confirm this upgrade
1. run `npx projen build` to upgrade API.md

### CODE REVIEW

**Comment by titanjer** [comment]
Hi @nlopezm, please review this.

**Comment by nlopezm** [comment]
> Hi @nlopezm, please review this.

Hey @titanjer! CI is failing https://github.com/nlopezm/aws-cdk-image-resize/actions/runs/3156652579/jobs/5249358989

**Comment by titanjer** [comment]
retest this please

**Comment by nlopezm** [comment]
Merged, thank you @titanjer!! 😄

**Pull request merged**
